module.exports = Object.freeze({
    NO_ACCOUNT: 'Please contact to admin as your account is not created yet or either it is inactive',
    INVALID_EXTENSION: 'Invalid file extension',
    SOMETHING_WRONG: 'Something went wrong',
    CREATED: 'Added successfully',
    UPDATE_SUCCESS: 'Updated successfully',
    NO_RECORD: 'No Record found',
    SOMETHING_WRONG: 'Something went wrong',
    RECORD_SUCCESS: 'Record found successfully',
    PERMISSION_DENIED: 'Permission denied',
    OTP_SENT: 'OTP sent successfully',
    ACCOUNT_NOT_ACTIVE: 'please register your account or provided otp is not correct',
    OTP_VERIFIED: 'Otp verified',
    INCORRECT_PASSWORD: 'Login failed ! Incorrect password',
    LOGIN_SUCCESSFULL: 'Login successfully',
    INVALID_TOKEN: 'Invalid token',
    NO_TOKEN: 'No token, authorization failed',
    PLEASE_ENTER_CORRECT_OLD_PASSWORD: 'Please enter correct old password',
    NEW_AND_OLD_PASSWORDS_CANNOT_BE_SAME: 'New and Old passwords cannot be the same',
    NEW_AND_CONFIRM_PASSWORDS_DO_NOT_MATCH: 'New and Confirm password fields do not match',
    PASSWORD_CHANGE_SUCCESS: 'Password changed successfully',
    PASSWORD_BLANK: "Password field should not be empty",
    OLD_USED_PASSWORD: "Password is already used please enter a new password",
    EMAIL_SUCCESS:"Email Send Successfully.!"
})