name: Deploy

# Trigger the workflow on push and pull request events on the deploy branch
on:
  push:
    branches: ["deploy"]
  pull_request:
    branches: ["deploy"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Ensure .scripts directory exists
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /home/bhavish/htdocs/www.testing.harshadkajale.online/Jaiswal-service-backend/.scripts

      - name: Upload Deployment Script
        uses: appleboy/scp-action@v0.1.6  # Use the latest version
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./.scripts/deploy.sh"
          target: "/home/bhavish/htdocs/www.testing.harshadkajale.online/Jaiswal-service-backend/.scripts/deploy.sh"

      - name: List files in .scripts directory for debug
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ls -l /home/bhavish/htdocs/www.testing.harshadkajale.online/Jaiswal-service-backend/.scripts

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6  # Replace with the latest version
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/bhavish/htdocs/www.testing.harshadkajale.online/Jaiswal-service-backend
            chmod +x ./.scripts/deploy.sh
            ./scripts/deploy.sh
