name: Deploy

on:
  push:
    branches: ["deploy"]
  pull_request:
    branches: ["deploy"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Verify Node.js and npm versions
        run: |
          node --version
          npm --version

      - name: Install SSH client
        run: |
          sudo apt-get update
          sudo apt-get install openssh-client -y

      - name: Deploy application
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} "cd /home/***/htdocs/www.testing.harshadkajale.online && npm install && npm start"
        env:
          SSH_AUTH_SOCK: /tmp/ssh_auth_sock
